# Buildpacks to include in builder
[[buildpacks]]
id = "wolfi-demo/java-maven"
version = "0.0.1"
uri = "../buildpacks/java-maven"

# Order used for detection
[[order]]
[[order.group]]
id = "wolfi-demo/java-maven"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "wolfi-base-stack"
run-image = "chainguard/stack-run:wolfi"
build-image = "chainguard/stack-build:wolfi"
